<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 
<!-- Created by XHQ Solution Builder Export on Jul 27, 2015 10:59:22 AM PDT -->
 
<!-- Begin DTD Validation section - DO NOT MODIFY THIS SECTION -->
<!DOCTYPE XHQ:SolutionConfig[
<!ELEMENT XHQ:SolutionConfig ((XHQ:Collection|XHQ:Component|XHQ:RenamedComponent|XHQ:RenamedGroup|XHQ:Group|XHQ:DataMember|XHQ:ComponentMember|XHQ:GroupMember|XHQ:CollectionMember)*,(XHQ:DeletedGroup|XHQ:DeletedComponent|XHQ:DeletedCollection)*)>
<!ATTLIST XHQ:SolutionConfig xmlns:XHQ       CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig ssHost          CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig rootName        CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig solutionRevID   CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig ssTime          CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig ssFormattedTime CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig xhqVersion      CDATA #IMPLIED>
<!ATTLIST XHQ:SolutionConfig xhqBuild        CDATA #IMPLIED>

<!ELEMENT XHQ:Collection (XHQ:ConnectProp*,XHQ:CacheProp*,XHQ:CacheIndexList*)>
<!ATTLIST XHQ:Collection xhqPath CDATA        #REQUIRED>
<!ATTLIST XHQ:Collection xhqComponent CDATA     #REQUIRED>
<!ATTLIST XHQ:Collection usage CDATA        #IMPLIED>
<!ATTLIST XHQ:Collection tagCollection (true|false)        #IMPLIED>
<!ATTLIST XHQ:Collection roles CDATA        #IMPLIED>
<!ATTLIST XHQ:Collection writes CDATA        #IMPLIED>
<!ATTLIST XHQ:Collection connectionGroup CDATA        #IMPLIED>

<!ELEMENT XHQ:Component EMPTY>
<!ATTLIST XHQ:Component xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:Component xhqComponent CDATA            #REQUIRED>
<!ATTLIST XHQ:Component usage CDATA            #IMPLIED>
<!ATTLIST XHQ:Component roles CDATA        #IMPLIED>

<!ELEMENT XHQ:RenamedComponent EMPTY>
<!ATTLIST XHQ:RenamedComponent xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:RenamedComponent renameTo CDATA            #REQUIRED>

<!ELEMENT XHQ:RenamedGroup EMPTY>
<!ATTLIST XHQ:RenamedGroup xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:RenamedGroup renameTo CDATA            #REQUIRED>

<!ELEMENT XHQ:Group EMPTY>
<!ATTLIST XHQ:Group xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:Group xhqComponent CDATA            #IMPLIED>
<!ATTLIST XHQ:Group usage CDATA            #IMPLIED>
<!ATTLIST XHQ:Group roles CDATA        #IMPLIED>

<!ELEMENT XHQ:DataMember (XHQ:HistorianConnectProp*,XHQ:ConnectProp*)>
<!ATTLIST XHQ:DataMember xhqPath CDATA        #REQUIRED>
<!ATTLIST XHQ:DataMember xhqComponent CDATA     #REQUIRED>
<!ATTLIST XHQ:DataMember xhqMember CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember usage CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember alias CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolOptimizeAuto (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolAllowWrite (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolConstrainMinimum (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolMinimum CDATA       #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolConstrainMaximum (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolMaximum CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolConstrainMask (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember datacontrolMask CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember expression CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember expressionSchedulerEnabled (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember expressionScheduleBaseTime CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember expressionSchedulePeriod CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember roles CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember writes CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historian CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historianRecord (true|false)        #IMPLIED>
<!ATTLIST XHQ:DataMember historianInterpolationType (Default|DEFAULT|Linear|LINEAR|Stepped|STEPPED)        #IMPLIED>
<!ATTLIST XHQ:DataMember historianCompression CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historianDeviation CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historianMinTime CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historianMaxTime CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historianName CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember historianConnectGroup CDATA        #IMPLIED>
<!ATTLIST XHQ:DataMember connectionGroup CDATA        #IMPLIED>

<!ELEMENT XHQ:ComponentMember (XHQ:ViewSecurity*)>
<!ATTLIST XHQ:ComponentMember xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:ComponentMember linkPath CDATA        #IMPLIED>
<!ATTLIST XHQ:ComponentMember xhqComponent CDATA            #REQUIRED>
<!ATTLIST XHQ:ComponentMember usage CDATA            #IMPLIED>
<!ATTLIST XHQ:ComponentMember roles CDATA        #IMPLIED>

<!ELEMENT XHQ:ViewSecurity EMPTY>
<!ATTLIST XHQ:ViewSecurity nameView CDATA             #IMPLIED>
<!ATTLIST XHQ:ViewSecurity rolesAllowed CDATA            #REQUIRED>

<!ELEMENT XHQ:GroupMember EMPTY>
<!ATTLIST XHQ:GroupMember xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:GroupMember xhqComponent CDATA            #IMPLIED>
<!ATTLIST XHQ:GroupMember usage CDATA            #IMPLIED>
<!ATTLIST XHQ:GroupMember roles CDATA        #IMPLIED>

<!ELEMENT XHQ:CollectionMember (XHQ:ViewSecurity*)>
<!ATTLIST XHQ:CollectionMember xhqPath CDATA             #REQUIRED>
<!ATTLIST XHQ:CollectionMember xhqComponent CDATA            #REQUIRED>
<!ATTLIST XHQ:CollectionMember usage CDATA            #IMPLIED>
<!ATTLIST XHQ:CollectionMember roles CDATA        #IMPLIED>
<!ATTLIST XHQ:CollectionMember linkCollection CDATA        #IMPLIED>
<!ATTLIST XHQ:CollectionMember linkConstraint CDATA        #IMPLIED>

<!ELEMENT XHQ:ConnectProp EMPTY>
<!ATTLIST XHQ:ConnectProp name CDATA             #REQUIRED>
<!ATTLIST XHQ:ConnectProp value CDATA            #REQUIRED>

<!ELEMENT XHQ:HistorianConnectProp EMPTY>
<!ATTLIST XHQ:HistorianConnectProp name CDATA             #REQUIRED>
<!ATTLIST XHQ:HistorianConnectProp value CDATA            #REQUIRED>

<!ELEMENT XHQ:CacheProp EMPTY>
<!ATTLIST XHQ:CacheProp name CDATA             #REQUIRED>
<!ATTLIST XHQ:CacheProp cacheMaxLength CDATA            #IMPLIED>
<!ATTLIST XHQ:CacheProp cachePrecision CDATA            #IMPLIED>
<!ATTLIST XHQ:CacheProp cacheScale CDATA            #IMPLIED>
<!ATTLIST XHQ:CacheProp subscribable (true|false)            #IMPLIED>
<!ATTLIST XHQ:CacheProp cacheUniqueKey (true|false)            #IMPLIED>

<!ELEMENT XHQ:CacheIndexList (XHQ:CacheIndexListMember*)>
<!ATTLIST XHQ:CacheIndexList name CDATA        #REQUIRED>

<!ELEMENT XHQ:CacheIndexListMember EMPTY>
<!ATTLIST XHQ:CacheIndexListMember name CDATA        #REQUIRED>
<!ATTLIST XHQ:CacheIndexListMember sort CDATA        #REQUIRED>

<!ELEMENT XHQ:DeletedCollection EMPTY>
<!ATTLIST XHQ:DeletedCollection name CDATA             #REQUIRED>
<!ELEMENT XHQ:DeletedGroup EMPTY>
<!ATTLIST XHQ:DeletedGroup name CDATA             #REQUIRED>
<!ELEMENT XHQ:DeletedComponent EMPTY>
<!ATTLIST XHQ:DeletedComponent name CDATA             #REQUIRED>

]>
<!-- End DTD Validation section -->
 
<XHQ:SolutionConfig
   xmlns:XHQ="http://www.siemens.com/indx"
   ssHost="localhost"
   rootName="VizionPacks"
   solutionRevID="836"
   ssTime="1438019962002"
   ssFormattedTime="Jul 27, 2015 10:59:22 AM PDT"
   xhqVersion="4.6"
   xhqBuild="258">
   <XHQ:Collection
      xhqPath="::COLLECTIONS.QMSamples"
      xhqComponent="XVQLabSample"
      usage="Quality Management - Lab Sample"
      roles="Solution Admins;Everyone"
      connectionGroup="XHQRC">
      <XHQ:ConnectProp
         name="DELTA_PERIOD"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="TS_REQUEST"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="INTERP_TYPE"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="USE_BUILDER"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="USE_PASS_THROUGH"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="SQL_STATEMENT"
         value="string:&quot;SELECT QMSample.sSampleName, Format(sSampleDateTime,&apos;dd-mmm-yyyy hh:nn&apos;), QMSample.iSampleDateTime, QMSample.sArea, QMSample.sUnit, QMSample.sCertifiedCheck, QMSample.sLotNumber, QMSample.sCntnrNo, QMSample.sCustomerName, QMSample.sNote, QMSample.sOtherSampleName, QMSample.sPackageName, QMSample.sProductName, QMSample.sProductSpecName, QMSample.sReceivedBy, Format(sReceivedDate,&apos;dd-mmm-yyyy hh:nn&apos;), QMSample.sResampleCheck, QMSample.sSampledBy, QMSample.sSamplePointName, QMSample.sSamplePriority, QMSample.sSampleStatus, QMSample.sTargetCompletionDate, QMSample.sTestCompletedCheck, QMSample.sHasOffSpecTest, Count(QMResults.sSampleName) AS CountOfsSampleName FROM QMSample INNER JOIN QMResults ON QMSample.sSampleName = QMResults.sSampleName GROUP BY QMSample.sSampleName, QMSample.sSampleDateTime, QMSample.iSampleDateTime, QMSample.sArea, QMSample.sUnit, QMSample.sCertifiedCheck, QMSample.sLotNumber, QMSample.sCntnrNo, QMSample.sCustomerName, QMSample.sNote, QMSample.sOtherSampleName, QMSample.sPackageName, QMSample.sProductName, QMSample.sProductSpecName, QMSample.sReceivedBy, QMSample.sReceivedDate, QMSample.sResampleCheck, QMSample.sSampledBy, QMSample.sSamplePointName, QMSample.sSamplePriority, QMSample.sSampleStatus, QMSample.sTargetCompletionDate, QMSample.sTestCompletedCheck, QMSample.sHasOffSpecTest; &quot;"
      />
      <XHQ:ConnectProp
         name="NUMBER_REFRESHES"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="POLL_PERIOD"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="USE_CUSTOM_POLL"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="MAPPED_MEMBERS"
         value="string[]:sSampleName;sSampleDateTime;iSampleDateTime;sArea;sUnit;sCertifiedCheck;sLotNumber;sCntnrNo;sCustomerName;sNote;sOtherSampleName;sPackageName;sProductName;sProductSpecName;sReceivedBy;sReceivedDate;sResampleCheck;sSampledBy;sSamplePointName;sSamplePriority;sSampleStatus;sTargetCompletionDate;sTestCompletedCheck;sOffSpec;iResultCount"
      />
      <XHQ:ConnectProp
         name="USE_REFRESH"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="USE_DELTA"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="VERSION"
         value="int:3"
      />
      <XHQ:CacheProp
         name="sArea"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sCertifiedCheck"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sCntnrNo"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sCustomerName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sLotNumber"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sNote"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sOtherSampleName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sPackageName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sProductName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sProductSpecName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sReceivedBy"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sReceivedDate"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sReceivedTime"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sResampleCheck"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSampleDateTime"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSampledBy"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSampleName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSamplePointName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSamplePriority"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSampleStatus"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sTargetCompletionDate"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sTargetCompletionTime"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sTestCompletedCheck"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sUnit"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sOffSpec"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sLabTagname"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
   </XHQ:Collection>
   <XHQ:CollectionMember
      xhqPath="::COLLECTIONS.QMSamples.colQMLabSampleResult"
      xhqComponent="XVQLabSampleResult"
      linkCollection="::Collections.QMResults"
      linkConstraint="where %sSampleName% = sSample"
      usage="QMLabSampleReuslt colleciton"
      roles="Solution Admins;Everyone">
   </XHQ:CollectionMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.iResultCount"
      xhqComponent="XVQLabSample"
      usage="Integer Test Result Count"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.iSampleDateTime"
      xhqComponent="XVQLabSample"
      usage="Integer Date"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sArea"
      xhqComponent="XVQLabSample"
      usage="String Area name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sCertifiedCheck"
      xhqComponent="XVQLabSample"
      usage="String Certified Check"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sCntnrNo"
      xhqComponent="XVQLabSample"
      usage="CntnrNo"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sCustomerName"
      xhqComponent="XVQLabSample"
      usage="String Customer Name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sLotNumber"
      xhqComponent="XVQLabSample"
      usage="String Lot Number "
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sNote"
      xhqComponent="XVQLabSample"
      usage="String Note"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sOtherSampleName"
      xhqComponent="XVQLabSample"
      usage="OtherSampleName"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sPackageName"
      xhqComponent="XVQLabSample"
      usage="String Package Name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sProductName"
      xhqComponent="XVQLabSample"
      usage="String Product name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sProductSpecName"
      xhqComponent="XVQLabSample"
      usage="String Product Specification"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sReceivedBy"
      xhqComponent="XVQLabSample"
      usage="String Received By"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sReceivedDate"
      xhqComponent="XVQLabSample"
      usage="String Received Date"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sReceivedTime"
      xhqComponent="XVQLabSample"
      usage="String Received Time"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sResampleCheck"
      xhqComponent="XVQLabSample"
      usage="String Resample Check"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sSampleDateTime"
      xhqComponent="XVQLabSample"
      usage="String Sample Date Time"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sSampledBy"
      xhqComponent="XVQLabSample"
      usage="String Sampled By"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sSampleName"
      xhqComponent="XVQLabSample"
      usage="String Sample name from ip_smpl"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sSamplePointName"
      xhqComponent="XVQLabSample"
      usage="String Sample Point name from ip_smpl"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sSamplePriority"
      xhqComponent="XVQLabSample"
      usage="String Sample Priority"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sSampleStatus"
      xhqComponent="XVQLabSample"
      usage="String Sample Status"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sTargetCompletionDate"
      xhqComponent="XVQLabSample"
      usage="String Target Completion Date"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sTargetCompletionTime"
      xhqComponent="XVQLabSample"
      usage="String Target Completion Time"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sTestCompletedCheck"
      xhqComponent="XVQLabSample"
      usage="String Test Completed Check"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sUnit"
      xhqComponent="XVQLabSample"
      usage="String Unit name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sOffSpec"
      xhqComponent="XVQLabSample"
      usage="Off Spec Test Result"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMSamples.sLabTagname"
      xhqComponent="XVQLabSample"
      usage="Lab Tagname"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:Collection
      xhqPath="::COLLECTIONS.QMResults"
      xhqComponent="XVQLabSampleResult"
      usage="Quality Management - Lab Sample Result"
      roles="Solution Admins;Everyone"
      connectionGroup="XHQRC">
      <XHQ:ConnectProp
         name="DELTA_PERIOD"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="TS_REQUEST"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="INTERP_TYPE"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="USE_BUILDER"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="USE_PASS_THROUGH"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="SQL_STATEMENT"
         value="string:&quot;SELECT QMSample.iSampleDateTime, QMResults.iSeq, QMSample.sArea, QMResults.sMax, QMResults.sMin, QMResults.sOffSpec, QMSample.sOtherSampleName, QMSample.sProductName, QMSample.sProductSpecName,  QMResults.sProperty, QMResults.sResult, QMSample.sSampleName,QMSample.sSampleName, Format(sSampleDateTime,&apos;dd-mmm-yyyy hh:nn&apos;),  QMSample.sSamplePointName, QMSample.sSampleStatus, QMResults.sSQCStatus, QMResults.sTechInit, QMResults.sTestMethod, QMSample.sUnit, QMResults.sUnits, Format(sEntryDate,&apos;dd-mmm-yyyy hh:nn&apos;), QMResults.sLabTagname FROM QMSample INNER JOIN QMResults ON QMSample.sSampleName = QMResults.sSampleName; &quot;"
      />
      <XHQ:ConnectProp
         name="NUMBER_REFRESHES"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="POLL_PERIOD"
         value="int:0"
      />
      <XHQ:ConnectProp
         name="USE_CUSTOM_POLL"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="MAPPED_MEMBERS"
         value="string[]:iDate;iSeq;sArea;sMax;sMin;sOffSpec;sOtherSampleName;sProduct;sProductSpec;sProperty;sResult;sSample;sSampleName;sSampleDate;sSamplePoint;sSampleStatus;sSQCStatus;sTechInit;sTestMethod;sUnit;sUnits;sEntryDate;sLabTagname"
      />
      <XHQ:ConnectProp
         name="USE_REFRESH"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="USE_DELTA"
         value="bool:false"
      />
      <XHQ:ConnectProp
         name="VERSION"
         value="int:3"
      />
      <XHQ:CacheProp
         name="sArea"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sEntryDate"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sIsGC"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sMax"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sMin"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sOffSpec"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sOtherSampleName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sProduct"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sProductSpec"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sProperty"
         cacheMaxLength="32"
         cacheUniqueKey="true"
      />
      <XHQ:CacheProp
         name="sResult"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSample"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSampleDate"
         cacheMaxLength="32"
         cacheUniqueKey="true"
      />
      <XHQ:CacheProp
         name="sSamplePoint"
         cacheMaxLength="32"
         cacheUniqueKey="true"
      />
      <XHQ:CacheProp
         name="sSampleStatus"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSQCStatus"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sTechInit"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sTestMethod"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sUnit"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sUnits"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sConfigField"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sLabTagname"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sEntryTime"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="sSampleName"
         cacheMaxLength="32"
         cacheUniqueKey="false"
      />
      <XHQ:CacheProp
         name="iDate"
         cacheUniqueKey="true"
      />
   </XHQ:Collection>
   <XHQ:CollectionMember
      xhqPath="::COLLECTIONS.QMResults.colResultHistory"
      xhqComponent="XVQLabSampleResult"
      linkCollection="::Collections.QMResults"
      linkConstraint="where sSamplePoint = %sSamplePoint% AND sProperty = %sProperty%"
      usage="Result History"
      roles="Solution Admins;Everyone">
   </XHQ:CollectionMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.iDate"
      xhqComponent="XVQLabSampleResult"
      usage="Integer Date"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.iSeq"
      xhqComponent="XVQLabSampleResult"
      usage="Property Sequence Number"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sArea"
      xhqComponent="XVQLabSampleResult"
      usage="Area"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sEntryDate"
      xhqComponent="XVQLabSampleResult"
      usage="Entry Date"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sIsGC"
      xhqComponent="XVQLabSampleResult"
      usage="Result is a GC Result"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sMax"
      xhqComponent="XVQLabSampleResult"
      usage="Max"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sMin"
      xhqComponent="XVQLabSampleResult"
      usage="Min"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sOffSpec"
      xhqComponent="XVQLabSampleResult"
      usage="Off Spec Result"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sOtherSampleName"
      xhqComponent="XVQLabSampleResult"
      usage="Other Sample Name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sProduct"
      xhqComponent="XVQLabSampleResult"
      usage="Product"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sProductSpec"
      xhqComponent="XVQLabSampleResult"
      usage="Product Spec"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sProperty"
      xhqComponent="XVQLabSampleResult"
      usage="Property"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sResult"
      xhqComponent="XVQLabSampleResult"
      usage="Result"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sSample"
      xhqComponent="XVQLabSampleResult"
      usage="Sample Name"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sSampleDate"
      xhqComponent="XVQLabSampleResult"
      usage="Sample Date"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sSamplePoint"
      xhqComponent="XVQLabSampleResult"
      usage="Sample Point"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sSampleStatus"
      xhqComponent="XVQLabSampleResult"
      usage="Sample Status"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sSQCStatus"
      xhqComponent="XVQLabSampleResult"
      usage="SQC Status"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sTechInit"
      xhqComponent="XVQLabSampleResult"
      usage="Technician Initials"
      roles="Solution Admins;Everyone"
      >
   </XHQ:DataMember>
   <XHQ:DataMember
      xhqPath="::COLLECTIONS.QMResults.sTestMethod"
      xhqComponent="XVQLabSampleResult"